### PR TITLE
added ScrollToPosition method

### PR DESCRIPTION
**Pull request by Herocod3r**
Allows programmatic scroll to position

### CODE REVIEW

**Comment by roubachof** [comment]
Thanks Man for the PR!
Any reason why not using the CurrentIndex property for this purpose? If you use it with dual binding and set it in your view model it should scroll to the matching view.

**Comment by roubachof** [comment]
FYI: int he next version (0.9.5) setting the CurrentIndex won't ignore the SnapStyle property and scroll to the given content accordingly. 

The proposed api changed was not implemented cause of several consistency:

1. For now the control doesn't support snap to end
2. Implementing scroll animation on Android would require a custom layout manager

**Comment by roubachof** [comment]
partially supported in 0.9.7

**Comment by Herocod3r** [comment]
Incase you need help with this project or any future projects, please dont forget to reach out.

**Pull request closed without merging**
